package id.ac.poliban.mi.yusfan.listtari;

import java.util.ArrayList;
import java.util.List;

public class DanceData {
    static List<Dance> getAllDance(){
        List<Dance> data = new ArrayList<>();
        {
            data.add(new Dance("https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/09_05_07_ngayah_GAMBUH_Batuan_%28_2007_%E2%80%94_PICs_%29_%E2%80%94_11_arya.jpg/375px-09_05_07_ngayah_GAMBUH_Batuan_%28_2007_%E2%80%94_PICs_%29_%E2%80%94_11_arya.jpg","Tari Bali","Tari Bali adalah tarian yang berasal dari Bali. Tari Bali tidak selalu bergantung pada alur cerita. Tujuan utama penari Bali adalah untuk menarikan tiap tahap gerakan dan rangkaian dengan ekspresi penuh. Kecantikan tari Bali tampak pada gerakan-gerakan yang abstrak dan indah. Tari-tari Bali yang paling dikenal antara lain pendet, gambuh, baris, sanghyang dan legong."));
            data.add(new Dance("https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Apsara_Dancer_Smile_of_Angkor_Theatre.jpg/330px-Apsara_Dancer_Smile_of_Angkor_Theatre.jpg", "Tari Dewi Aspara", "Tari Dewi Apsara (របាំទេពអប្សរា: Robam Tep Apsara) adalah sebuah tarian klasik Khmer yang diciptakan oleh Sendratari Kerajaan Kamboja pada pertengahan abad ke-20 di bawah perlindungan Ratu Sisowath Kossamak. Apsara diperankan dan ditarikan oleh perempuan yang mengenakan pakaian yang pas melilit tubuh mereka, serta mengenakan pehiasan dan mahkota yang mewah dan indah,[1] sementara gerakan tariannya telah disesuaikan dengan pakem tari klasik Kamboja yang menggambarkan mitologi klasik dan kisah religius Hindu mengenai mitos bidadari apsara penghuni swargaloka nan cantik jelita."));
            data.add(new Dance("https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/TsangMonk.jpg/375px-TsangMonk.jpg", "Tari Dunhuang", "Tari Dunhuang adalah kumpulan tari dari tari tradisional Cina yang terinspirasi dari fresko (lukisan dinding) di daerah Dunhuang, provinsi Gansu, di Barat Cina.[1] Tarian di Dunhuang ini banyak terpengaruh oleh agama Buddha.[2] Tarian ini benar-benar mencerminkan kekayaan budaya Cina"));
            data.add(new Dance("https://i2.wp.com/www.romadecade.org/wp-content/uploads/2018/09/Tari-Saman-Dari-Aceh.jpg?w=800&ssl=1", "Tari Saman", "Dari beberapa tarian tradisional lainnya, mungkin tari ini yang paling banyak dikenal. Tari saman merupakan tari tradisional dari Aceh yang bisa dibilang paling banyak memiliki anggota. Tari ini biasanya dihadirkan pada saat upacara-upacara adat ataupun acara keagamaan. Tarian ini biasanya beranggotakan sekelompok orang dengan jumlah yang ganjil. Salah satu keunikan dari tari Saman ini adalah suara yang dihasilkan dari para pukulan tangan para penari yang memiliki alunan yang seragam. Tari saman ditampilkan dengan cara duduk, rapi, dan berjajar yang tidak sama dengan tarian lainnya yang biasanya melakukan gerakan bebas."));
            data.add(new Dance("https://i0.wp.com/www.romadecade.org/wp-content/uploads/2018/09/Tari-Tor-Tor-Dari-Sumatera-Utara.jpg?resize=768%2C402&ssl=1", "Tari Tor-Tor", "Tarian yang satu ini selalu diiringi dengan alunan musik gondang yang merupakan salah satu kebudayaan masyarakat batak. Selain musik, para penari juga diharuskan untuk memakai kain khas tradisional suku Batak yang bernama Ulos. Ulos yang dipakai para penari Tor-Tor biasanya memiliki warna dengan dominasi hitam dan merah. Tari Tor-Tor biasanya digunakan dalam upacara-upacara adat ataupun acara sakral lainnya yang berfungsi untuk melakukan penyambutan dalam menghormati Sang Pencipta dan para leluhur masyarakat Sumatera Utara."));
            data.add(new Dance("https://i1.wp.com/www.romadecade.org/wp-content/uploads/2018/09/Tari-Piring-Dari-Sumatera-Barat.jpg?resize=768%2C513&ssl=1", "Tari Piring", "Tentunya tarian tradisional yang satu ini sudah banyak diketahui masyarakat Indonesia. Tarian yang menggunakan properti piring ini berasal dari Sumatera Barat. Setiap penari yang melakukan tarian diharuskan membawa 2 buah piring yang diletakkan pada kedua telapak tangannya. Seolah sudah ahli dan terlatih. Piring-piring tersebut tidak akan pernah jatuh saat penari melakukan tariannya. Para penari mengayunkan piring-piring tersebut secara perlahan, lembut, dan teratur. Di iringi dengan musik khas Sumatera, membuat tarian ini semakin indah untuk dinikmati. Tari Piring biasanya digunakan untuk menyambut kedatangan tamu agung ke Sumatera Barat ataupun acara-acara kebudayaan masyarakat setempat."));
            data.add(new Dance("https://i2.wp.com/www.romadecade.org/wp-content/uploads/2018/09/Tari-Serimpi-Dari-Yogyakarta.jpg?w=700&ssl=1", "Tari Serimpi", "Kota Yogyakarta memang dikenal sebagai kota yang masih menyimpan banyak misteri, mitos, dan kepercayaan terhadap hal-hal yang sakral. Tak terkecuali dengan tari tradisional yang dimilikinya. Tari Serimpi menjadi tarian sakral kota Yogyakarta yang menggambarkan keanggunan dan kesopanan. Hal tersebut dapat dilihat dari gerakannya yang lemah gemulai. Tari Serimpi biasanya dihadirkan pada saat upacara atau acara adat Keraton pada saat acara Kenegaraan ataupun Kenaikan Tahta Sultan. Karena tariannya yang bersifat sakral, para penarinya pun tak boleh dari kalangan sembarangan. Melainkan masih keturunan atau kerabat Keraton dari dalam kerajaan."));
        }
        return data;
    }

}
